### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aistBMRG** [imgag/ngs-bits#38]
Hi,

When running atropos detect, I am experiences issues for some files; as follows:

Run1Sam03_S3_R1_001.fastq.gz
2019-05-20 12:17:34,008 INFO: This is Atropos 1.1.21 with Python 3.6.7
2019-05-20 12:17:34,011 INFO: Detecting adapters and other potential contaminant sequences based on 12-mers in 10000 reads
2019-05-20 12:17:38,409 ERROR: Unknown error
Traceback (most recent call last):
  File "/Volumes/mikami/bio/apps/12.04/sw/atropos/1.1.21/lib/python3.6/site-packages/atropos/util/__init__.py", line 727, in run_interruptible
    func(*args, **kwargs)
  File "/Volumes/mikami/bio/apps/12.04/sw/atropos/1.1.21/lib/python3.6/site-packages/atropos/commands/base.py", line 32, in __call__
    self.finish(command_runner.summary, **kwargs)
  File "/Volumes/mikami/bio/apps/12.04/sw/atropos/1.1.21/lib/python3.6/site-packages/atropos/commands/detect/__init__.py", line 481, in finish
    for match in self.read1_detector.matches(**kwargs)
  File "/Volumes/mikami/bio/apps/12.04/sw/atropos/1.1.21/lib/python3.6/site-packages/atropos/commands/detect/__init__.py", line 373, in matches
    self._filter_and_sort(**kwargs)
  File "/Volumes/mikami/bio/apps/12.04/sw/atropos/1.1.21/lib/python3.6/site-packages/atropos/commands/detect/__init__.py", line 390, in _filter_and_sort
    matches = self._get_contaminants()
  File "/Volumes/mikami/bio/apps/12.04/sw/atropos/1.1.21/lib/python3.6/site-packages/atropos/commands/detect/__init__.py", line 617, in _get_contaminants
    cur = results[0]
IndexError: list index out of range

My command line is as follows:

for x in *_R1_001.fastq.gz; do
atropos detect \
--no-default-contaminants --no-cache-contaminants \
-pe1 ${x%%_*}_S*_R1_001.fastq.gz \
-pe2 ${x%%_*}_S*_R2_001.fastq.gz \
--detector heuristic \
--max-reads 1000000 \
--output ${x%%_*}_atropos.txt
done

Would it be clarify the source of this issue?

Thank you.

Dieter

**Comment by marc-sturm** [comment]
I guess you should ask the question here:
https://github.com/jdidion/atropos

Best,
  Marc

**Comment by aistBMRG** [comment]
Thank you -- added an issue there.

Dieter
